// Code generated by Slice Machine. DO NOT EDIT.

import BlogContent from './BlogContent';
import Image from './Image';

export {
	BlogContent,
	Image,
};

export const components = {
	blog_content: BlogContent,
	image: Image,
};
